In [1]:
#import files
import pandas as pd
import numpy as np
import seaborn as sbn
data = pd.read_csv('Raw-Data.csv')
data.shape

(16, 7)

In [2]:
data.head()

,Country,Age,Gender,Symptoms,Experiencing_Symptoms,Severity,Contact
0,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Yes
1,Italy,10-19,Female,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing","Pains,Nasal-Congestion,Runny-Nose",Moderate,No
2,Iran,20-24,Transgender,"Fever,Tiredness,Dry-Cough","Pains,Nasal-Congestion",Severe,Dont-Know
3,Republic of Korean,25-59,NaN,"Fever,Tiredness",Pains,None,NaN
4,France,60+,NaN,Fever,"Nasal-Congestion,Runny-Nose,Diarrhea",NaN,NaN

In [3]:
country = len(data.Country.dropna().unique())
age = len(data.Age.dropna().unique())
gender = len(data.Gender.dropna().unique())
symptoms = len(data.Symptoms.dropna().unique())
esymptoms = len(data.Experiencing_Symptoms.dropna().unique())
severity = len(data.Severity.dropna().unique())
contact = len(data.Contact.dropna().unique())

print("Total Combination Possible: ",country * age * gender * symptoms * esymptoms * severity * contact)

Total Combination Possible:  316800

In [4]:
#combination of columns
import itertools
columns = [data.Country.dropna().unique().tolist(),
          data.Age.dropna().unique().tolist(),
          data.Gender.dropna().unique().tolist(),
          data.Symptoms.dropna().unique().tolist(),
          data.Experiencing_Symptoms.dropna().unique().tolist(),
          data.Severity.dropna().unique().tolist(),
          data.Contact.dropna().unique().tolist()]

data_frame = pd.DataFrame(list(itertools.product(*columns)), columns=data.columns)

In [5]:
data_frame.shape

(316800, 7)

In [6]:
data_frame.head()

,Country,Age,Gender,Symptoms,Experiencing_Symptoms,Severity,Contact
0,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Yes
1,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,No
2,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Dont-Know
3,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Moderate,Yes
4,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Moderate,No

In [7]:
#make columns by symptoms values
symptoms_list = data_frame['Symptoms'].str.split(',')

from collections import Counter
symptoms_counter = Counter(([a for b in symptoms_list.tolist() for a in b]))

for symptom in symptoms_counter.keys():
    data_frame[symptom] = 0
    data_frame.loc[data_frame['Symptoms'].str.contains(symptom), symptom] = 1

data_frame.head()

,Country,Age,Gender,Symptoms,Experiencing_Symptoms,Severity,Contact,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton
0,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Yes,1,1,1,1,1,0
1,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,No,1,1,1,1,1,0
2,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Dont-Know,1,1,1,1,1,0
3,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Moderate,Yes,1,1,1,1,1,0
4,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Moderate,No,1,1,1,1,1,0

In [8]:
#make columns by xperiencing_Symptoms values

esymptoms_list = data_frame['Experiencing_Symptoms'].str.split(',')

from collections import Counter
esymptoms_counter = Counter(([a for b in esymptoms_list.tolist() for a in b]))

for esymptom in esymptoms_counter.keys():
    data_frame[esymptom] = 0
    data_frame.loc[data_frame['Experiencing_Symptoms'].str.contains(esymptom), esymptom] = 1

data_frame.head()

,Country,Age,Gender,Symptoms,Experiencing_Symptoms,Severity,Contact,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,None_Experiencing
0,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Yes,1,1,1,1,1,0,1,1,1,1,0
1,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,No,1,1,1,1,1,0,1,1,1,1,0
2,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Dont-Know,1,1,1,1,1,0,1,1,1,1,0
3,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Moderate,Yes,1,1,1,1,1,0,1,1,1,1,0
4,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Moderate,No,1,1,1,1,1,0,1,1,1,1,0

In [9]:
#Symptoms,Experiencing_Symptoms coluns deletion
data_frame = data_frame.drop(['Symptoms','Experiencing_Symptoms'],axis=1)
dummy = pd.get_dummies(data_frame.drop('Country',axis=1))
dummy['Country'] = data_frame['Country']
data_frame = dummy
data_frame.head()

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country
0,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,0,1,China
1,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,0,China
2,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,1,0,0,China
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,0,1,China
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,1,0,China

In [10]:
#final_data.to_csv('Cleaned-Data.csv', index=False, header=True)
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   None_Sympton             316800 non-null  int64
 6   Pains                    316800 non-null  int64
 7   Nasal-Congestion         316800 non-null  int64
 8   Runny-Nose               316800 non-null  int64
 9   Diarrhea                 316800 non-null  int64
 10  None_Experiencing        316800 non-null  int64
 11  Age_0-9                  316800 non-null  uint8
 12  Age_10-19                316800 non-null  uint8
 13  Age_20-24                316800 non-null  uint8
 14  Age_25-59                316800 non-null  uint8
 15  Age_60+                  316800 non-null  uint8
 16  Gender_Female            316800 non-null  uint8
 17  Gender_Male              316800 non-null  uint8
 18  Gender_Transgender       316800 non-null  uint8
 19  Severity_Mild            316800 non-null  uint8
 20  Severity_Moderate        316800 non-null  uint8
 21  Severity_None            316800 non-null  uint8
 22  Severity_Severe          316800 non-null  uint8
 23  Contact_Dont-Know        316800 non-null  uint8
 24  Contact_No               316800 non-null  uint8
 25  Contact_Yes              316800 non-null  uint8
 26  Country                  316800 non-null  object
dtypes: int64(11), object(1), uint8(15)
memory usage: 33.5+ MB

In [11]:
data_frame = data_frame.drop(['Gender_Female','Gender_Male','Gender_Transgender','Severity_Moderate','Severity_None','Severity_Severe','Contact_Dont-Know','Contact_No','Contact_Yes','Country','None_Experiencing','None_Sympton','Age_0-9','Age_10-19','Age_20-24','Age_25-59','Age_60+'],axis=1)

In [12]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   Pains                    316800 non-null  int64
 6   Nasal-Congestion         316800 non-null  int64
 7   Runny-Nose               316800 non-null  int64
 8   Diarrhea                 316800 non-null  int64
 9   Severity_Mild            316800 non-null  uint8
dtypes: int64(9), uint8(1)
memory usage: 22.1 MB

In [13]:

#preparing dataset by ignoring the infection '1' when the symptoms are '0' 

for counter in range(len(data_frame)):
    if data_frame.loc[counter,'Fever']  == 1 and data_frame.loc[counter,'Tiredness'] == 1  and data_frame.loc[counter,'Dry-Cough'] == 1  and data_frame.loc[counter,'Difficulty-in-Breathing'] == 1 and data_frame.loc[counter,'Sore-Throat'] == 1 and data_frame.loc[counter,'Pains'] == 1 and data_frame.loc[counter,'Nasal-Congestion'] == 1 and data_frame.loc[counter,'Runny-Nose'] == 1 and data_frame.loc[counter,'Runny-Nose'] == 1:
        data_frame.loc[counter,'Severity_Mild']  = 1
    else: 
            data_frame.loc[counter,'Severity_Mild']  = 0

In [14]:
data_frame

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,Severity_Mild
0,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,0,0,0,0,0
316796,0,0,0,0,0,0,0,0,0,0
316797,0,0,0,0,0,0,0,0,0,0
316798,0,0,0,0,0,0,0,0,0,0
316799,0,0,0,0,0,0,0,0,0,0

In [15]:
df  = data_frame.rename(columns = {'Severity_Mild':'infected'})
#df_new = df.rename(columns={'A': 'a'}, index={'ONE': 'one'})
df

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,infected
0,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,0,0,0,0,0
316796,0,0,0,0,0,0,0,0,0,0
316797,0,0,0,0,0,0,0,0,0,0
316798,0,0,0,0,0,0,0,0,0,0
316799,0,0,0,0,0,0,0,0,0,0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   Pains                    316800 non-null  int64
 6   Nasal-Congestion         316800 non-null  int64
 7   Runny-Nose               316800 non-null  int64
 8   Diarrhea                 316800 non-null  int64
 9   infected                 316800 non-null  uint8
dtypes: int64(9), uint8(1)
memory usage: 22.1 MB

In [17]:
df['infected'].value_counts()

0    313200
1      3600
Name: infected, dtype: int64

In [18]:
df.to_csv('Cleaned-Data.csv', index=False, header=True)

In [19]:
df.drop(df[df['infected']  < 1].index, inplace = True) 
#filtered_df
df

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,infected
0,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
314707,1,1,1,1,1,1,1,1,0,1
314708,1,1,1,1,1,1,1,1,0,1
314709,1,1,1,1,1,1,1,1,0,1
314710,1,1,1,1,1,1,1,1,0,1
314711,1,1,1,1,1,1,1,1,0,1

In [20]:
df['infected'].value_counts()

1    3600
Name: infected, dtype: int64

In [21]:
#final_data.rename(columns = {'Severity_Mild':'infected'})

In [23]:
df.to_csv('Cleaned-Data2.csv', index=False, header=True)